- README.md
As stated in the description, Rclone is an open-source cloud storage tool that supports the encryption of files in the cloud.
> Addition of Rclone to the cloud storage section

- README.md
Added postmarketOS and PureOS to Linux based phone operating systems; Added Odysee to YouTube alternatives
> Add postmarketOS and PureOS; Add Odysee

- README.md
Easy to use web-based image-scrubber by @everestpipkin. AFAIK the entire tool is loaded into the browser's cache and no data hits the server itself.
> Cloaking: image-scrubber

- README.md
- SaidIt runs on the old reddit source code. Most API endpoints are the same and the site functions similarly to reddit
- Ruqqus is a newer alternative that doesn't have censorship and collects no user data
> Added SaidIt and Ruqqus to Reddit alternatives

- README.md
> Add category office

- README.md
added Linux as recommended OS for PC.
(that's my first submitted pull request. Please let me know if I did something wrong or if I need to change anything)
> added_OS_for_PC

- README.md
This is a great list of privacy tools! I built a Reddit frontend in Rust and thought it would suit `awesome-privacy` well.
> Add Libreddit as Reddit frontend

- README.md
It is a great alternative to Photoshop. 
https://github.com/KDE/krita
https://krita.org/en
> Add Krita to Photo management

- README.md
Not sure if this is the right way to introduce the new entry.
> Add new entry for 2FA

- README.md
A featureful GPL-licenced Android Expense Tracking App, distributed also on F-droid
> Adding My Expenses app

- README.md
Hello, I've added to the analytics list my project Aurora.
> Added aurora to analytics list

- README.md
Add MeshCentral to Remote Access and Control tools
> Add MeshCentral to Remote Access and Control tools

- README.md
> docs: remove retired website lbry.tv

- README.md
We have a specifically pro-privacy mission statement, no tracking, and a commitment to continue with this :-)
> Added Beekeeper Studio

- README.md
Added some foss android launchers.
> Add open source android launchers

- README.md
Hello,
I've added petal maps due to them being created by Huawei which has allegedly worked with the Chinese government.
This was added because of issue #91 
I've also added Organic maps from issue #88 
Thanks.
> Add petal maps to avoid & add organic maps

- README.md
Added Inkscape which is an alternative to Adobe Illustrator
Also added Nextcloud notes, for both PC and Android. 
I think there should be a separate category for nextcloud services. Maybe something like "alternative ecosystem" should do.
> Inkscape & Nextcloud Notes

- README.md
Added LibreWolf to Desktop list under Web Browser
This is my first pull request and I'm new to Git so let me know if I did something wrong, thank you
> Added LibreWolf

- README.md
Also add [dzr](https://github.com/yne/dzr) as libre client alternative for Android, Linux, BSD
> Add deezer music section

- README.md
A version of Android's default WebView with privacy enabled by default.
> Added Bromite WebView

- README.md
Homepage: https://ackee.electerious.com/
> Add Ackee analytics software

- README.md
Mull is a LibreWolf alternative for android
> Add Mull Browser

- README.md
> Change wording and link repository for Piped.

- README.md
and that you don't have to use them through web sites
> mention TranslateLocally (FOSS NMT)

- README.md
Github for project is here https://github.com/simplex-chat/simplex-chat
> Added SimpleX chat to instant messaging section

- README.md
[Visited](https://github.com/yuis-ice/visited) is a privacy-friendly browser utility that collects browsing history locally to a SQLite database file.
> add Visited

- README.md
- Fixed [#issue160](https://github.com/pluja/awesome-privacy/issues/160). Alphabetically sorted content sections. Made content positions match with content index.
- added posidon launcher and pie launcher
- added hCaptcha
- added OrangeWebsite and 1984 hosting
- added Quillnote
- added DivestOS
- removed qwant as data is collected and shared with third parties
https://about.qwant.com/en/legal/confidentialite/
https://tosdr.org/en/service/527
> Fixed #issue160 and other additions

- README.md
Updated the website to their new one
> Update LibreWolf website

- README.md
I've updated the description for SimpleX Chat for consistency.
I'm synchronising these amongst the awesome projects that we have been featured on and the source repo.
> Updated SimpleX Chat for consistency.

- README.md
Added dawn app for reddit, and added information about brave search's independence from other search engines
> Added Dawn and clarification about brave search

- README.md
ImageGlass is a lightweight software application whose purpose is to help you view images in a clean and intuitive working environment.
It gives you the possibility to view over 80+ common image formats, including .gif, .svg, .png, .heic, ... and many more advanced features which help normal users or designers speed up their work.
Privacy policy is available here: https://imageglass.org/privacy
> Add ImageGlass

- README.md
If you want to know more about theses alternatives clients/modifications of Discord, go to my [README.md]( https://github.com/MatadorProBr/awesome-privacy/blob/patch-1/README.md#video-and-audio-conferencing) and see they.
Also the disclaimer says that these modifications [violates](https://nitter.net/discord/status/1006178587731550208#m) the [Discord ToS](https://discord.com/terms) and we are not responsible of any suspension or termination of your account but this should [not happen **yet**](https://github.com/GooseMod/GooseMod/wiki/FAQ#is-goosemod-against-discord-tos).
> Add various alternatives/modifications of Discord and a disclaimer

- README.md
nb: I co-develop RethinkDNS + Firewall.
It is also rec'd by [privacyguides.org](https://github.com/privacyguides/privacyguides.org/discussions/241).
> Android: RethinkDNS + Firewall

- README.md
The entire repository is about privacy, but i think that is important to add some security warnings too.
> Add security warning on the Android "field"

- README.md
Hi!
I'm the maintainer of Swetrix - an [opensource](https://github.com/swetrix) Google Analytics alternative.
Would be happy to see my service on your list!
> Add Swetrix

- README.md
Freezer is unavailable due to copyright infringement.
> Remove Freezer

- README.md
As in the contributing guidelines, I added [Skiff](http://skiff.com/) - end-to-end encrypted mail and collaboration - to the relevant sections with a brief description.
> Add Skiff resources

- README.md
Adds ViMusic: a free, no ad, no login YouTube Music client.
> Add ViMusic

- README.md
https://github.com/liameno/librengine Privacy Web Search Engine
> Add librengine

- README.md
https://withcabin.com
No cookies or consent banners
Faster, lighter and greener
No data sharing or ad networks
Compliant with all privacy laws
> Added Cabin Analytics

- README.md
Full featured self-hosted email solution using Docker.
> Add mailcow: dockerized

- README.md
Proton Drive was [officially launched](https://proton.me/blog/proton-drive-launch) last week.
> Add Proton Drive

- README.md
One of the more normal open-source launchers available on F-Droid.
> Add Bliss Launcher

- README.md
* https://github.com/jonaswinkler/paperless-ng/issues/1599
* https://github.com/jonaswinkler/paperless-ng/issues/1632
> added paperless-ngx

- README.md
Remove EOL client mods
- Goosemod
- Cumcord
- Powercord
Replace with alternatives
- Vencord
- Replugged
> Remove EOL client mods and add alternatives

- README.md
Hey @pluja 
as discussed removing Telegram.
Cheers,
Peter
> rm telegram

- README.md
Updated the link to the newest Linux Mint Cinnamon Edition.
> Updated the link to the newest Linux Mint Cinnamon Edition

- README.md
Disclaimer: I am the owner of monerosms.com - but i created the service because I was not happy with existing competition in the space
> Add monerosms.com to online phone providers

- README.md
@pluja I think keyoxide.org might be a good link in bio tool and an alternative to tools like LinkTree to share personal link / social media portfolios. Please share your suggestion.
> add keyoxide.org

- README.md
Hey @pluja. I took the liberty of moving this as the first item in the list, as it is the only one from the list that is cross platform, and it matches (or is better than) the existing entries in all other aspects. But I might be thinking biased (since I'm one of the developers), so please feel free to reorder.
Some mentions/reviews:
- [New oil - Twitter mention](https://twitter.com/thenewoil1/status/1602077944611995649)
- [Detailed review at zeroclick.xyz](https://zeroclick.xyz/ente-auth)
- [FOSS Android - Mastodon review](https://mstdn.social/@foss_android/109505185418700364)
And here is the original blog post introducing it - https://ente.io/blog/auth/
Thank you!
> Add ente Auth - Free / Cross Platform / E2EE 2FA app

- README.md
Trilium Notes is another note taking application that allows you to self host it
> Add Trilium Notes

- README.md
Wasabi Wallet is an important tool for improving privacy that should be shared. It is a reputable wallet featured on https://bitcoin.org/en/wallets/desktop/windows/wasabi/
cc @yahiheb
> include Wasabi Wallet in list of Bitcoin tools

- README.md
im suprised it isn't here already
> add ungoogled chromium

- README.md
[Forward Email](https://forwardemail.net) (@forwardemail) - the 100% open-source and privacy-focused email service.
> Added Forward Email

- README.md
Restic is a modern backup program that can back up large amounts of files reliably, efficiently and safely. Key features of restic include git like versioning at no extra cost, de-duplication, impressive compression while still maintaining end-to-end encryption. S3 like storage systems can be used with restic to store personal data without a worry of being read.
> Adding Restic

- README.md
Hi, this is Aaron from Least Authority. We have developed two new file transfer tools built on Magic Wormhole that are free and open-source. We would be pleased to have them included on your Awesome list.
> Add two Magic Wormhole implementations

- README.md
Hi, Aaron from Least Authority again. We would be very happy to have our new privacy focused, open-source, cloud storage product included in your Awesome list. Thanks for the consideration.
> Add PrivateStorage

- README.md
Add information and link to independent audit.
> Update ente Photos

- README.md
https://mullvad.net/en/browser
> Added Mullvad Browser under web browsers (desktop)

- README.md
The section name should be `trackers`  to match the table of contents.
> Fix menstrual cycle trackers link

- README.md
Here's a link to [skiff](https://skiff.com/drive) drive.
> Added Skiff Drive - End to end encrypted alternative to google drive

- README.md
Full disclosure: I'm the author of [Loggit](https://loggit.net).
Loggit is end-to-end encrypted and open source (AGPL-3.0). Additionally, 3.0 is self-hosted. You can read more about [that announcement here](https://loggit.net/blog/announcing-loggit-3.0-self-hostable).
The website also has no analytics or tracking (only page views are counted when loaded).
> Add Loggit

- README.md
I'm currently [reviewing](https://jrxtx.notion.site/TODOs-and-NOTES-free-private-and-in-cloud-e5e24179897d4e478039423a5bc82a40?pvs=4) (in progress) "Notes and Task apps" applications, and I've noticed a significant oversight: there's absent an application Anytype that, in my opinion, is one of the best open-source options in this category, if not the best.
> Anytype notes app

- README.md
see: https://github.com/openboard-team/openboard/issues/828
> Removed Dead Project 

- README.md
I think that Qubes-OS deserves to be on this list as it is a really uniquely secured and privacy-preserving OS by its design.
> Added Qubes-OS to PC OS list in README.md

- README.md
Added version control category, with entries for Github, Codeberg, Forgejo and Gitlab.
> Add version control category

- README.md
Updated formatting to use the inbuilt markdown [alerts](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) formatting. Example:
> [!NOTE]
> This is a note.
> [!IMPORTANT]
> This is _important_.
>[!TIP]
> This is a tip!
- https://github.blog/changelog/2023-12-14-new-markdown-extension-alerts-provide-distinctive-styling-for-significant-content/
> Update notes/warning/tips formatting in README.md

- README.md
An annotation system which is based upon XMPP PubSub.
> Add Blasta

- README.md
Ephemeral zero-knowledge sensitive data sharing platform with web, cli, and chrome-extension clients. It offers a suite of configurations beyond the standard, including max read count, IP/CIDR allow-listing, and webhooks.
> Add crypt.fyi

- README.md
DivestOS is no longer maintained. closes: #504
> remove DivestOS (discontinued)

- README.md
[tnyr.me](https://tnyr.me) is a privacy respecting URL shortener with passwordless end-to-end encryption.
> add tnyr.me link shortener

- README.md
Gokapi is a file sharing service written in Go that allows anonymous downloads and authentication-restricted uploads. Authentication can be configured to be basic or SSO using OAuth 2.0.
GitHub: https://github.com/Forceu/Gokapi
> Add Gokapi, a secure file sharing option
