pluja/awesome-privacy

README.md
KeepassDX is only an Android client. I replaced it with KeepassXC which is available for many (desktop) platforms and also added sub-sections for clients on other platforms (including KeepassDX for Android).
=> Replace KeepassDX with KeepassXC

README.md
Commit 587c27ad06281b40e1cdee4e161c15b8bf7bc7fa changed the heading from «Streaming Platforms» to «Streaming Platforms (Twitch)». Updated the link accordingly.
=> Fix Heading of «Streaming Platforms (Twitch)»

README.md
If the users don't trust the official Bitwarden server, they can self-host their own but a lighter weight version, albeit unofficial.
=> Add vaultwarden

README.md
Add DuckDuckGo as a privacy respecting search engine.
=> Add DuckDuckGo

README.md
After 5 years since it's inception, Daniel Quinn [archived the repository](https://github.com/the-paperless-project/paperless) as he couldn't maintain it anymore. In the meantime, Jonas Winkler, forked it as [Paperless-ng](https://github.com/jonaswinkler/paperless-ng), reworking it, improving the UI and, in general, supercharging the already excelent project.
This pull request aims to replace the Paperless repository link to the Paperless-ng respository link, as it currently maintained and constantly updated. However, as the original Paperless is not deprecated (only archived) a link to the original repository is still added with a notice of archival.
=> Change Paperless to Paperless-ng as Paperless is now archived

README.md
Add https://nullitics.com (open source version is at https://github.com/nullitics/nullitics) to the list of privacy-focused web analytics tools.
=> Add nullitics.com

README.md
F-Droid doesn't find it when searching for "pocketpaint", the official name is "pocket paint".
=> Add space to Pocket Paint name

README.md
Point users directly towards the app on F-Droid, instead of the source code repository
=> Update link for Mull

README.md
Took the description from their `<meta property="og:description">` tag
=> Add pirsch to analytics

README.md
The tag on "Operative systems > Android" redirects to "Photo Editing and Management", so this fixes that
=> Fix tags mistake

README.md
It's [AnonAddy](https://github.com/anonaddy) not Anonaddy, it's [SimpleLogin](https://github.com/simplelogin) not Simplelogin, and it's [Riseup](https://github.com/riseupnet) not RiseUp.
=> Fix Capitalization Issues

README.md
There is no iOS client for Fritter as seen on https://fritter.cc/ or https://github.com/jonjomckay/fritter
(Which is quite unfortunate as I was looking for an iOS app front-end for Twitter...)
=> Remove mention of iOS from Fritter

README.md
https://translate.metalune.xyz/ has been deprecated
=> Fix SimplyTranslate link

README.md
`Aulicord` to `Aliucord` spelling fix
=> Fix Aluicord spelling

README.md
Passky is simple, lightweight, easy to use and open source passowrd manager.
It's one of the easiest cloud-based password manage to self-host.
=> Add Passky

README.md
Addtional spotify clients for Android.
xManager: lets you build spotify with additonal features like black Amoled background and ad blocking (Warning this manager has ads which can be turned off) https://github.com/xManager-v2/xManager-Spotify
Blade Player: Open source Spotify client which actually works without Premium. Although they say premium is needed.
missing some features that normal Spotify have. https://github.com/vhaudiquet/BladePlayer
=> Added Spotify clients for android

README.md
First of all, thanks @pluja for creating this awesome curated list :raised_hands: 
I'm suggesting you to add [LessPass](https://www.lesspass.com) to the FOSS list on the Password manager's section. I'm not related in any way with LessPass, I've just been using it for years, and I love it! 
If you haven't tried yet, I'm suggesting you to do it :wink: 
To create a password you'll provide:
- Domain of the website you are loging in
- Username or email you are using
- A master password (the only password you actually need to remember)
- Several customizable options such as length o which characters include/exclude
This will create a password that you can use for the domain & user you specified. The awesome thing of LessPass is that **is not storing it anywhere**. Next time you want to login in …
=> Add LessPass to Password manager's section

README.md
Hi, I'd like to suggest a tool we made at [blindnet](https://blindnet.io) to be added to the list. 
* [Blindsend](https://github.com/blindnet-io/blindsend) - Open source tool for private, end-to-end encrypted file exchange.
* **License**: MIT Licence
* **Why do you think this helps users privacy?**: Many users still use e-mail or non-encrypted file-transfer services to exchange sensitive (and often confidential) files. Even professionals (lawyers, doctors) request personal and sensitive data from their clients to be sent by e-mail. Blindsend encrypts files in the browser, before they reach the internet. It is easy to use, even for non-technical users. The parties exchanging files can remain anonimous.
* **Under what section should this service be listed?**: File Management and Sharing
* …
=> Add blindsend to File Management and Sharing

README.md
Added the following under the photo storage alternatives:
- [Ente](https://ente.io/) - End-to-end encrypted storage for photos and videos, with family plans and options to share photos and videos with friends. Open source apps.
Thank you!
=> Add ente - E2EE photo storage

README.md
DropBox's name was missing under Cloud Storage. You could only see the tosdr embed. Fixed it.
=> DropBox name was missing

README.md
Hey @pluja 
Aurora seems to be gone: the domain is parked. I couldn't find a Github. 
It feels the better approach to take it off the list. What do you think?
Cheers,
Peter
=> Removing Aurora

README.md
Both of the listed front-ends for Instagram are dead, the fork for Barinsta has been dead for months (https://blog.avalos.me/2021/08/14/barinsta/), and Bibliogram just closed a few weeks ago (https://bibliogram.art/). All remaining public instances that are still up for Bibliogram lead to a 504 Gateway Time-out when trying to search anything.
All Redirection apps and extensions in the use Bibliogram, so their mention of Instagram should be removed.
=> Remove Instagram section and mention of Instagram from Redirection apps and exentsions

README.md
I was looking for privacy minded alternatives for the popular read it later service Pocket, and was surprised to not find these tools in the list.
So after some searching I came across some privacy-unfriendly services of which Pocket seems to be king. I am not entirely sure about Raindrop.io, but it does seem to be just-another-data-hoarder with a pretty and well phrased privacy policy.
Wallabag was so far the only well designed alternative I could find. If more pop up, I'll add these (or someone else can). It doesn't have fancy (or up to date) phone apps, but it does adhere well to the idea of a privacy focused service which can be accessed by any browser.
=> Add Read-It-Later (such as Pocket) alternative

README.md
Hey @pluja 
I've removed the "coming soon" note on Berty - it's available now. 
I was also wondering if Telegram is actually to recommend. The background story doesn't check out IMHO, rolling it's own encryption and the risk of political involvement (Russian ownership) is high. Let me know if you want me to remove it.
Cheers,
Peter
=> "Remove coming soon"-note for Berty

README.md
Scribe's source has moved from https://sr.ht/~edwardloveall/scribe/ to https://git.sr.ht/~edwardloveall/scribe/
=> Fix link to scribe's source

README.md
Doom Captcha is nowhere near secure and JUST DISABLING JAVASCRIPT (which most bots do) is enough to disable it
DON'T EVER USE IT IN A PROJECT
=> Remove Doom Captcha

README.md
The sentence:
> You need to be really careful when using Bitcoin so you don't leave any traces that can later be used against you to harm your privacy.
Is not actionable and does not provide the user with any information on _how_ they can use Bitcoin without leaving traces, so it was removed.
This commit provides two FOSS options, one for Android, and one for desktop, to allow Bitcoin to be used in a more private manner.
=> Add privacy tools to Bitcoin

README.md
I am not entirely sure whether Status can be considered entirely p2p, however it for sure does not belong next to Signal or Threema.  
For reference, the communication protocol stands on Waku (https://waku.org/)
=> Moving Status messenger to "Decentralized"

README.md
This fork is discontinued, it was merged back into `libreddit` a few months ago.
https://github.com/ferritreader/ferrit
=> Remove `ferrit`

README.md
Links for Microsoft Service and Google in this section are swapped; this should fix them. Google Hangouts renamed to Google Meet, the modern service name; this change may be necessary in other places.
=> Fix "Teamworking Tools" ToSDR links for Microsoft and Google 

README.md
Resolves #339.
It seems that https://github.com/Metastem/wikiless is the maintained fork of Wikiless and some of the instances in the readme are using this version. The linked instance is the one marked as `(Official)` in the [readme](https://github.com/Metastem/wikiless#instances).
=> Update Wikiless links

README.md
https://blog.stingle.org/2023/04/stingle-photos-api-server-is-open-source-now/
=> Stingle Photos have published the server code, allowing self-hosting

README.md
Added SRB2Kart, OpenBoard, and OpenBoard upgrade, and replaced Mineclone5 with Mineclonia, as Mineclone5 has been deleted from the website and Mineclonia is a updated version.
=> Add SRB2Kart, OpenBoard, Openboard upgrade, and Mineclonia

README.md
Skiff is defunct and shutting down in 6 months, this PR removes it.
https://skiff.com/data-migration
=> fix: removed Skiff (since defunct and shutting down in 6 months)

README.md
* [Unidentified Analytics](https://unidentifiedanalytics.web.app/) - Naive ip-based cross-plafform tracking, useful in websites, shell scripts, and anywhere you can post images or call urls. Source code available at [actuallymentor/unidentified-analytics](https://github.com/actuallymentor/unidentified-analytics)
* **License**: MIT
* **Why do you think this helps users privacy?**: It tracks no personally identifiable data from the person doing the tracking, and the person being tracked.
* **Under what section should this service be listed?**: Analytics
* **Additional comments / info**: I made this tool to track the usage of my moderately popular [mac battery limiting tool](https://github.com/actuallymentor/battery). It's a very convenient way to add "minimum viable tracking" to open source …
=> Add Unidentified Analytics

README.md
Quillnote seems to have been abandoned : it hasn't been updated for two years and links to official website and Play Store app don't work anymore.
Therefore I replaced it with an active fork, [Quillpad](https://github.com/quillpad/quillpad).
=> Replace Quillnote by Quillpad

README.md
RavioOTP has recently been updated to delete users' keys and ask for money.
Fixes issue #398.
=> Remove RavioOTP

README.md
Updated the name of LinkFree to BioDrop as it has been renamed. See https://github.com/pluja/awesome-privacy/issues/444
=> Replace LinkFree with BioDrop

README.md
Qwant is a privacy oriented search engine made in France, so it complies with European Laws, which are more restrictive in privacy regulations. More info: [https://about.qwant.com/en/search/](url)
=> Added Qwant to the list of Search Engines

README.md
Upon closer inspection, OOPSpam is not what it seems, it directly violates GDPR in several ways (but the website says it's compliant) and the website uses third-party tracking cookies, namely tolt.io for affiliate marketing.
Highlights from the [OOPSpam's Privacy Policy](https://www.oopspam.com/privacypolicy):
- (!) OOPSpam.com transfers your data outside your jurisdiction - "Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction."
- (!) OOPSpam.com is using your data "to provide and improve the Service.". It is unclear whether its the submitted user data or customer's personal information. …
=> Remove OOPSpam - not privacy-friendly

README.md
The [Samourai Wallet](https://samouraiwallet.com/) domain and mobile app was seized by the Department of Justice after the founders were arrested a couple of months ago. I suggest we remove this as a recommended option from the list.
To maintain consistency with the rest of the doc, I've also replaced the `CAUTION` note with a `WARNING` quote, but I can revert it if we don't like it.
**Source:** https://www.coindesk.com/policy/2024/04/24/samourai-wallet-founders-arrested-and-charged-with-money-laundering/
=> Remove `Samourai Wallet` from Payments

README.md
The Blackhole repository has been removed from GitHub.
While [someone has reuploaded it](https://github.com/StarsWarrior/BlackHole), I have not reviewed this new repository. For now, it seems best not to include Blackhole in the list.
=> Remove blackhole (removed from Github)

README.md
darktable is a tool designed for amateur and professional photographs. It differs from other tools in the list in multiple ways that make it relevant for a different audience :
- It does both management and editing in a single app. You can think of it as a combination of DigiKam + GIMP
- It accepts raw files : these files are an equivalent of negatives in film photography. Working on these instead of JPEGs adds a lot of editing capabilities and improves the quality of the result
- Editing is non-destructive : all your editions are stored in a text file. What you see in darktable is a preview of the result. The actual work on your image is only performed when you export it. This allows trial and error without deteriorating your image and/or managing multiple versions of the file by …
=> Add darktable for photo management and editing

README.md
It seems SimplyTranslate moved their source code to codeberg. New repo URL is taken from their [Demo](https://simplytranslate.org/) website.
=> Updated simplytranslate source code URL

README.md
Floccus is free and open-source software (MPL 2.0, see [Github repository](https://github.com/floccusaddon/floccus).
It is different from other solutions in the list because it is not a self-hosted bookmark manager, it just uses a little space in any cloud or Git repository your already have. That makes it more accessible for most people, I suppose.
=> Added Floccus for bookmarking

README.md
Hi there!
I would like to ask for my new open-source app called AliasVault to be included in the awesome-privacy list. AliasVault is an open-source and end-to-end encrypted password manager with a built-in email server. It helps you by creating alternative identities, passwords and email addresses for every website you use. It's fully open-source and you can use the cloud-hosted version or self-host it on your own server.
I've checked all the requirements:
For more information about AliasVault:
- Online demo (cloud hosted): https://www.aliasvault.net/
- GitHub repo and installation instructions: https://github.com/lanedirt/AliasVault
- Documentation: https://docs.aliasvault.net/
I hope AliasVault can be included in the list so more people can find it. Thanks for your time!
=> Add AliasVault - open source password manager with built-in email server

README.md
Based on the title of the repo, Jetispot is not been maintained since Mar 30, 2024
=> Drop Jetispot
